/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duan1.ui;

import com.duan1.helper.Auth;
import com.duan1.helper.ChuyenManHinh;
import com.duan1.helper.DanhMuc;
import com.duan1.helper.ImageHelper;
import com.duan1.helper.MsgBox;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        try {
            UIManager.setLookAndFeel(new com.jtattoo.plaf.mint.MintLookAndFeel());
        } catch (Exception e) {
        }
        initComponents();
        init();
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);
        cmh.setView(pnlTrangChu, lblTrangChu);
        List<DanhMuc> listItem = new ArrayList<>();

        listItem.add(new DanhMuc("TrangChu", pnlTrangChu, lblTrangChu));
        listItem.add(new DanhMuc("NguoiDung", pnlNguoiDung, lblNguoiDung));
        listItem.add(new DanhMuc("SinhVien", pnlSinhVien, lblSinhVien));
        listItem.add(new DanhMuc("Sach", pnlSach, lblSach));
        listItem.add(new DanhMuc("PhieuMuon", pnlPhieuMuon, lblPhieuMuon));
        cmh.setEvent(listItem);

//         nút setting
        pnlSetting.setEnabled(false);
        pnlSetting.setVisible(false);
        lblSet1.setEnabled(false);
        lblSet1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlTieuDe = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        pnlView = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        pnlTrangChu = new javax.swing.JPanel();
        lblmn1 = new javax.swing.JLabel();
        lblTrangChu = new javax.swing.JLabel();
        pnlNguoiDung = new javax.swing.JPanel();
        lblmn2 = new javax.swing.JLabel();
        lblNguoiDung = new javax.swing.JLabel();
        pnlSinhVien = new javax.swing.JPanel();
        lblmn3 = new javax.swing.JLabel();
        lblSinhVien = new javax.swing.JLabel();
        pnlSach = new javax.swing.JPanel();
        lblmn4 = new javax.swing.JLabel();
        lblSach = new javax.swing.JLabel();
        pnlPhieuMuon = new javax.swing.JPanel();
        lblmn5 = new javax.swing.JLabel();
        lblPhieuMuon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlset = new javax.swing.JPanel();
        lblSet2 = new javax.swing.JLabel();
        lblSet1 = new javax.swing.JLabel();
        pnlSetting = new javax.swing.JPanel();
        lblDX = new javax.swing.JLabel();
        lblKT = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDMK = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniLoaiSach = new javax.swing.JMenuItem();
        mniSach = new javax.swing.JMenuItem();
        mniSinhVien = new javax.swing.JMenuItem();
        mniPhieuMuon = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniNguoiDung = new javax.swing.JMenuItem();
        mnuThongTin = new javax.swing.JMenu();
        mniNXB = new javax.swing.JMenuItem();
        mniTacGia = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniPM = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THƯ VIỆN");

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("HỆ THỐNG QUẢN LÝ THƯ VIỆN");

        javax.swing.GroupLayout pnlTieuDeLayout = new javax.swing.GroupLayout(pnlTieuDe);
        pnlTieuDe.setLayout(pnlTieuDeLayout);
        pnlTieuDeLayout.setHorizontalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTieuDeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTieuDeLayout.setVerticalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMenu.setBackground(new java.awt.Color(42, 39, 41));

        pnlTrangChu.setBackground(new java.awt.Color(42, 39, 41));
        pnlTrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblmn1.setBackground(new java.awt.Color(192, 27, 54));
        lblmn1.setOpaque(true);

        lblTrangChu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTrangChu.setForeground(new java.awt.Color(204, 204, 204));
        lblTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/home_1.png"))); // NOI18N
        lblTrangChu.setText("      Home");
        lblTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlTrangChuLayout = new javax.swing.GroupLayout(pnlTrangChu);
        pnlTrangChu.setLayout(pnlTrangChuLayout);
        pnlTrangChuLayout.setHorizontalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangChuLayout.createSequentialGroup()
                .addComponent(lblmn1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTrangChuLayout.setVerticalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangChuLayout.createSequentialGroup()
                .addComponent(lblmn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlNguoiDung.setBackground(new java.awt.Color(42, 39, 41));
        pnlNguoiDung.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblmn2.setBackground(new java.awt.Color(192, 27, 54));

        lblNguoiDung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNguoiDung.setForeground(new java.awt.Color(204, 204, 204));
        lblNguoiDung.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/u.png"))); // NOI18N
        lblNguoiDung.setText("      Người dùng");
        lblNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNguoiDungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNguoiDungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNguoiDungMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlNguoiDungLayout = new javax.swing.GroupLayout(pnlNguoiDung);
        pnlNguoiDung.setLayout(pnlNguoiDungLayout);
        pnlNguoiDungLayout.setHorizontalGroup(
            pnlNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiDungLayout.createSequentialGroup()
                .addComponent(lblmn2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNguoiDungLayout.setVerticalGroup(
            pnlNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiDungLayout.createSequentialGroup()
                .addComponent(lblmn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlSinhVien.setBackground(new java.awt.Color(42, 39, 41));
        pnlSinhVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblmn3.setBackground(new java.awt.Color(192, 27, 54));

        lblSinhVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSinhVien.setForeground(new java.awt.Color(204, 204, 204));
        lblSinhVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/st1.png"))); // NOI18N
        lblSinhVien.setText("     Sinh viên");
        lblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSinhVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSinhVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSinhVienMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSinhVienLayout = new javax.swing.GroupLayout(pnlSinhVien);
        pnlSinhVien.setLayout(pnlSinhVienLayout);
        pnlSinhVienLayout.setHorizontalGroup(
            pnlSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSinhVienLayout.createSequentialGroup()
                .addComponent(lblmn3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSinhVienLayout.setVerticalGroup(
            pnlSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSinhVienLayout.createSequentialGroup()
                .addComponent(lblmn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblSinhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlSach.setBackground(new java.awt.Color(42, 39, 41));
        pnlSach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblmn4.setBackground(new java.awt.Color(192, 27, 54));

        lblSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSach.setForeground(new java.awt.Color(204, 204, 204));
        lblSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/bk1.png"))); // NOI18N
        lblSach.setText("     Sách");
        lblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSachMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSachMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSachLayout = new javax.swing.GroupLayout(pnlSach);
        pnlSach.setLayout(pnlSachLayout);
        pnlSachLayout.setHorizontalGroup(
            pnlSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSachLayout.createSequentialGroup()
                .addComponent(lblmn4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSachLayout.setVerticalGroup(
            pnlSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSachLayout.createSequentialGroup()
                .addComponent(lblmn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlPhieuMuon.setBackground(new java.awt.Color(42, 39, 41));
        pnlPhieuMuon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblmn5.setBackground(new java.awt.Color(192, 27, 54));

        lblPhieuMuon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhieuMuon.setForeground(new java.awt.Color(204, 204, 204));
        lblPhieuMuon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/bill.png"))); // NOI18N
        lblPhieuMuon.setText("     Phiếu mượn");
        lblPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhieuMuonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPhieuMuonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPhieuMuonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlPhieuMuonLayout = new javax.swing.GroupLayout(pnlPhieuMuon);
        pnlPhieuMuon.setLayout(pnlPhieuMuonLayout);
        pnlPhieuMuonLayout.setHorizontalGroup(
            pnlPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhieuMuonLayout.createSequentialGroup()
                .addComponent(lblmn5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );
        pnlPhieuMuonLayout.setVerticalGroup(
            pnlPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhieuMuonLayout.createSequentialGroup()
                .addComponent(lblmn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblPhieuMuon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(42, 39, 41));

        pnlset.setBackground(new java.awt.Color(102, 102, 102));

        lblSet2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSet2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/settings.png"))); // NOI18N
        lblSet2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSet2MouseClicked(evt);
            }
        });

        lblSet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/settings.png"))); // NOI18N
        lblSet1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSet1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlsetLayout = new javax.swing.GroupLayout(pnlset);
        pnlset.setLayout(pnlsetLayout);
        pnlsetLayout.setHorizontalGroup(
            pnlsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSet2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
            .addGroup(pnlsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSet1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
        );
        pnlsetLayout.setVerticalGroup(
            pnlsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSet2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addGroup(pnlsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSet1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        pnlSetting.setBackground(new java.awt.Color(102, 102, 102));

        lblDX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDX.setText("Đăng xuất");
        lblDX.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDXMouseMoved(evt);
            }
        });
        lblDX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDXMouseClicked(evt);
            }
        });

        lblKT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblKT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKT.setText("Kết thúc");
        lblKT.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblKTMouseMoved(evt);
            }
        });
        lblKT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSettingLayout = new javax.swing.GroupLayout(pnlSetting);
        pnlSetting.setLayout(pnlSettingLayout);
        pnlSettingLayout.setHorizontalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSettingLayout.setVerticalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingLayout.createSequentialGroup()
                .addComponent(lblDX, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKT, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSinhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPhieuMuon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(pnlTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlRootLayout = new javax.swing.GroupLayout(pnlRoot);
        pnlRoot.setLayout(pnlRootLayout);
        pnlRootLayout.setHorizontalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlRootLayout.setVerticalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addComponent(pnlTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnuHeThong.setText("Hệ thống");

        mniDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Refresh.png"))); // NOI18N
        mniDMK.setText("Đổi mật khẩu");
        mniDMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDMKActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDMK);

        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Exit.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);
        mnuHeThong.add(jSeparator1);

        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Stop.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniKetThuc);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setText("Quản lý");

        mniLoaiSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/ls1.jpg"))); // NOI18N
        mniLoaiSach.setText("Loại sách");
        mniLoaiSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoaiSachActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniLoaiSach);

        mniSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/sach1.jpg"))); // NOI18N
        mniSach.setText("Sách");
        mniSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSachActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniSach);

        mniSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/User.png"))); // NOI18N
        mniSinhVien.setText("Sinh Viên");
        mniSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSinhVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniSinhVien);

        mniPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Text.png"))); // NOI18N
        mniPhieuMuon.setText("Phiếu mượn");
        mniPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPhieuMuonActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniPhieuMuon);
        mnuQuanLy.add(jSeparator2);

        mniNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/User group.png"))); // NOI18N
        mniNguoiDung.setText("Người dùng");
        mniNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNguoiDungActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNguoiDung);

        jMenuBar1.add(mnuQuanLy);

        mnuThongTin.setText("Thông tin");

        mniNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/nxb.jpg"))); // NOI18N
        mniNXB.setText("Nhà xuất bản");
        mniNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNXBActionPerformed(evt);
            }
        });
        mnuThongTin.add(mniNXB);

        mniTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/tg.png"))); // NOI18N
        mniTacGia.setText("Tác giả");
        mniTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTacGiaActionPerformed(evt);
            }
        });
        mnuThongTin.add(mniTacGia);

        jMenuBar1.add(mnuThongTin);

        mnuThongKe.setText("Thống kê");

        mniPM.setText("Thống kê phiếu mượn");
        mniPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPMActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniPM);

        jMenuBar1.add(mnuThongKe);

        mnuTroGiup.setText("Trợ giúp");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Globe.png"))); // NOI18N
        jMenuItem11.setText("Hướng dẫn sử dụng");
        mnuTroGiup.add(jMenuItem11);
        mnuTroGiup.add(jSeparator3);

        mniGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Brick house.png"))); // NOI18N
        mniGioiThieu.setText("Giới thiệu phần mềm");
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniGioiThieu);

        jMenuBar1.add(mnuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseClicked
        // TODO add your handling code here:
        bar(lblmn1);
    }//GEN-LAST:event_lblTrangChuMouseClicked

    private void lblTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseEntered
        // TODO add your handling code here:
        pnlTrangChu.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_lblTrangChuMouseEntered

    private void lblTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseExited
        // TODO add your handling code here:
        pnlTrangChu.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_lblTrangChuMouseExited

    private void lblNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNguoiDungMouseClicked
        // TODO add your handling code here:
        bar(lblmn2);
    }//GEN-LAST:event_lblNguoiDungMouseClicked

    private void lblNguoiDungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNguoiDungMouseEntered
        // TODO add your handling code here:
        pnlNguoiDung.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_lblNguoiDungMouseEntered

    private void lblNguoiDungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNguoiDungMouseExited
        // TODO add your handling code here:
        pnlNguoiDung.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_lblNguoiDungMouseExited

    private void lblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSinhVienMouseClicked
        // TODO add your handling code here:
        bar(lblmn3);
    }//GEN-LAST:event_lblSinhVienMouseClicked

    private void lblSinhVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSinhVienMouseEntered
        // TODO add your handling code here:
        pnlSinhVien.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_lblSinhVienMouseEntered

    private void lblSinhVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSinhVienMouseExited
        // TODO add your handling code here:
        pnlSinhVien.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_lblSinhVienMouseExited

    private void lblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSachMouseClicked
        // TODO add your handling code here:
        bar(lblmn4);
    }//GEN-LAST:event_lblSachMouseClicked

    private void lblSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSachMouseEntered
        // TODO add your handling code here:
        pnlSach.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_lblSachMouseEntered

    private void lblSachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSachMouseExited
        // TODO add your handling code here:
        pnlSach.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_lblSachMouseExited

    private void lblPhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuMuonMouseClicked
        // TODO add your handling code here:
        bar(lblmn5);
    }//GEN-LAST:event_lblPhieuMuonMouseClicked

    private void lblPhieuMuonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuMuonMouseEntered
        // TODO add your handling code here:
        pnlPhieuMuon.setBackground(Color.decode("#565255"));
    }//GEN-LAST:event_lblPhieuMuonMouseEntered

    private void lblPhieuMuonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuMuonMouseExited
        // TODO add your handling code here:
        pnlPhieuMuon.setBackground(Color.decode("#2a2729"));
    }//GEN-LAST:event_lblPhieuMuonMouseExited

    private void lblSet2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSet2MouseClicked
        // TODO add your handling code here:
        pnlSetting.setEnabled(true);
        pnlSetting.setVisible(true);
        lblSet1.setEnabled(true);
        lblSet1.setVisible(true);
        lblSet2.setEnabled(false);
        lblSet2.setVisible(false);
    }//GEN-LAST:event_lblSet2MouseClicked

    private void lblSet1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSet1MouseClicked
        // TODO add your handling code here:
        pnlSetting.setEnabled(false);
        pnlSetting.setVisible(false);
        lblSet1.setEnabled(false);
        lblSet1.setVisible(false);
        lblSet2.setEnabled(true);
        lblSet2.setVisible(true);
    }//GEN-LAST:event_lblSet1MouseClicked

    private void mniNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNXBActionPerformed
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);
        if (Auth.isLogin()) {
            cmh.setNXB(mniNXB);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_mniNXBActionPerformed

    private void mniTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTacGiaActionPerformed
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);

        if (Auth.isLogin()) {
            cmh.setTG(mniTacGia);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_mniTacGiaActionPerformed

    private void lblKTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKTMouseClicked
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc ?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblKTMouseClicked

    private void lblKTMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKTMouseMoved
        // TODO add your handling code here:
        lblKT.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblKTMouseMoved

    private void lblDXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDXMouseClicked
        // TODO add your handling code here:
        Auth.clear();
        new DangNhapJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblDXMouseClicked

    private void lblDXMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDXMouseMoved
        // TODO add your handling code here:
        lblDX.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblDXMouseMoved

    private void mniLoaiSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoaiSachActionPerformed
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);

        if (Auth.isLogin()) {
            cmh.setLoaiSach(mniLoaiSach);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_mniLoaiSachActionPerformed

    private void mniSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSachActionPerformed
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);

        if (Auth.isLogin()) {
            cmh.setSach(mniSach);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_mniSachActionPerformed

    private void mniSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSinhVienActionPerformed
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);

        if (Auth.isLogin()) {
            cmh.setSinhVien(mniSinhVien);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_mniSinhVienActionPerformed

    private void mniPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPhieuMuonActionPerformed
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);

        if (Auth.isLogin()) {
            cmh.setPhieuMuon(mniPhieuMuon);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_mniPhieuMuonActionPerformed

    private void mniNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNguoiDungActionPerformed
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);

        if (Auth.isLogin()) {
            cmh.setNguoiDung(mniNguoiDung);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_mniNguoiDungActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        Auth.clear();
        new DangNhapJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc ?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void mniDMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDMKActionPerformed
        // TODO add your handling code here:
        this.openDoiMatKhau();
    }//GEN-LAST:event_mniDMKActionPerformed

    private void mniPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPMActionPerformed
        // TODO add your handling code here:
        this.openThongKePM();
    }//GEN-LAST:event_mniPMActionPerformed

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed
        // TODO add your handling code here:
        new GioiThieuJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mniGioiThieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblDX;
    private javax.swing.JLabel lblKT;
    private javax.swing.JLabel lblNguoiDung;
    private javax.swing.JLabel lblPhieuMuon;
    private javax.swing.JLabel lblSach;
    private javax.swing.JLabel lblSet1;
    private javax.swing.JLabel lblSet2;
    private javax.swing.JLabel lblSinhVien;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JLabel lblmn1;
    private javax.swing.JLabel lblmn2;
    private javax.swing.JLabel lblmn3;
    private javax.swing.JLabel lblmn4;
    private javax.swing.JLabel lblmn5;
    private javax.swing.JMenuItem mniDMK;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniLoaiSach;
    private javax.swing.JMenuItem mniNXB;
    private javax.swing.JMenuItem mniNguoiDung;
    private javax.swing.JMenuItem mniPM;
    private javax.swing.JMenuItem mniPhieuMuon;
    private javax.swing.JMenuItem mniSach;
    private javax.swing.JMenuItem mniSinhVien;
    private javax.swing.JMenuItem mniTacGia;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuThongTin;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNguoiDung;
    private javax.swing.JPanel pnlPhieuMuon;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSach;
    private javax.swing.JPanel pnlSetting;
    private javax.swing.JPanel pnlSinhVien;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JPanel pnlTrangChu;
    private javax.swing.JPanel pnlView;
    private javax.swing.JPanel pnlset;
    // End of variables declaration//GEN-END:variables
    void init() {
        setLocationRelativeTo(null);
        this.setIconImage(ImageHelper.getAppIcon());
        new ChaoJDialog(this, true).setVisible(true);
        DangNhapJDialog dn = new DangNhapJDialog(this, true);
        dn.setVisible(true);
//        QR qr = new QR();
    }

    void startDoHo() {
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date now = new Date();
                // chuyển đổi thời gian sang chuỗi dưới dạng giờ phút giây ta dùng hàm SimpleDateFormat
                // +hh: giờ     mm:phút     ss:giây     a: là buổi trong ngày (vd: sáng, chiều)
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                String text = formater.format(now);
//                lbldongho.setText(text);
            }
        }).start();
    }

    public void bar(JLabel lab) {
        lblmn4.setOpaque(false);
        lblmn3.setOpaque(false);
        lblmn5.setOpaque(false);
        lblmn1.setOpaque(false);
        lblmn2.setOpaque(false);
        lab.setOpaque(true);
        pnlMenu.repaint();
    }

    void openDoiMatKhau() {
        if (Auth.isLogin()) {
            new DoiMatKhauJDiaglog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    void openThongKePM() {
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);
        if (Auth.isLogin()) {
            cmh.setTK(mniPM);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }

}
