/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duan1.ui;

import com.duan1.helper.Auth;
import com.duan1.helper.ChuyenManHinh;
import com.duan1.helper.DanhMuc;
import com.duan1.helper.MsgBox;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class TrangChuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrangChuJPanel
     */
    public TrangChuJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlView = new javax.swing.JPanel();
        pnlNguoiDung = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlSinhVien = new javax.swing.JPanel();
        lblSinhVien = new javax.swing.JLabel();
        pnlLoaiSach = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlSach = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlPhieuMuon = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlThongKe = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(678, 478));

        pnlNguoiDung.setBackground(new java.awt.Color(255, 255, 255));
        pnlNguoiDung.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlNguoiDungMouseMoved(evt);
            }
        });
        pnlNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNguoiDungMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/nguoidung.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlNguoiDungLayout = new javax.swing.GroupLayout(pnlNguoiDung);
        pnlNguoiDung.setLayout(pnlNguoiDungLayout);
        pnlNguoiDungLayout.setHorizontalGroup(
            pnlNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNguoiDungLayout.setVerticalGroup(
            pnlNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlSinhVien.setBackground(new java.awt.Color(255, 255, 255));
        pnlSinhVien.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlSinhVienMouseMoved(evt);
            }
        });
        pnlSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSinhVienMouseClicked(evt);
            }
        });

        lblSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/sinhvien.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlSinhVienLayout = new javax.swing.GroupLayout(pnlSinhVien);
        pnlSinhVien.setLayout(pnlSinhVienLayout);
        pnlSinhVienLayout.setHorizontalGroup(
            pnlSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSinhVienLayout.setVerticalGroup(
            pnlSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlLoaiSach.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoaiSach.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlLoaiSachMouseMoved(evt);
            }
        });
        pnlLoaiSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLoaiSachMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/loaisach.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlLoaiSachLayout = new javax.swing.GroupLayout(pnlLoaiSach);
        pnlLoaiSach.setLayout(pnlLoaiSachLayout);
        pnlLoaiSachLayout.setHorizontalGroup(
            pnlLoaiSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLoaiSachLayout.setVerticalGroup(
            pnlLoaiSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlSach.setBackground(new java.awt.Color(255, 255, 255));
        pnlSach.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlSachMouseMoved(evt);
            }
        });
        pnlSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSachMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/sach.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlSachLayout = new javax.swing.GroupLayout(pnlSach);
        pnlSach.setLayout(pnlSachLayout);
        pnlSachLayout.setHorizontalGroup(
            pnlSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSachLayout.setVerticalGroup(
            pnlSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlPhieuMuon.setBackground(new java.awt.Color(255, 255, 255));
        pnlPhieuMuon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlPhieuMuonMouseMoved(evt);
            }
        });
        pnlPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPhieuMuonMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/phieumuon.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlPhieuMuonLayout = new javax.swing.GroupLayout(pnlPhieuMuon);
        pnlPhieuMuon.setLayout(pnlPhieuMuonLayout);
        pnlPhieuMuonLayout.setHorizontalGroup(
            pnlPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPhieuMuonLayout.setVerticalGroup(
            pnlPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlThongKe.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongKe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseMoved(evt);
            }
        });
        pnlThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/thongke.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLoaiSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLoaiSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlNguoiDungMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoiDungMouseMoved
        // TODO add your handling code here:
        pnlNguoiDung.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnlNguoiDungMouseMoved

    private void pnlNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoiDungMouseClicked
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);
        if (Auth.isLogin()) {
            cmh.setNguoiDung(pnlNguoiDung);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_pnlNguoiDungMouseClicked

    private void pnlSinhVienMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSinhVienMouseMoved
        // TODO add your handling code here:
        pnlSinhVien.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnlSinhVienMouseMoved

    private void pnlSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSinhVienMouseClicked
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);
        if (Auth.isLogin()) {
            cmh.setSinhVien(pnlSinhVien);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }//GEN-LAST:event_pnlSinhVienMouseClicked

    private void pnlLoaiSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLoaiSachMouseClicked
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);
        if (Auth.isLogin()) {
            cmh.setLoaiSach(pnlLoaiSach);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_pnlLoaiSachMouseClicked

    private void pnlLoaiSachMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLoaiSachMouseMoved
        // TODO add your handling code here:
        pnlLoaiSach.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnlLoaiSachMouseMoved

    private void pnlThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseClicked
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);
        if (Auth.isLogin()) {
            cmh.setThongKe(pnlThongKe);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_pnlThongKeMouseClicked

    private void pnlThongKeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseMoved
        // TODO add your handling code here:
        pnlThongKe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnlThongKeMouseMoved

    private void pnlSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSachMouseClicked
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);
        if (Auth.isLogin()) {
            cmh.setSach(pnlSach);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_pnlSachMouseClicked

    private void pnlSachMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSachMouseMoved
        // TODO add your handling code here:
        pnlSach.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnlSachMouseMoved

    private void pnlPhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPhieuMuonMouseClicked
        // TODO add your handling code here:
        ChuyenManHinh cmh = new ChuyenManHinh(pnlView);
        if (Auth.isLogin()) {
            cmh.setPhieuMuon(pnlPhieuMuon);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }

    }//GEN-LAST:event_pnlPhieuMuonMouseClicked

    private void pnlPhieuMuonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPhieuMuonMouseMoved
        // TODO add your handling code here:
        pnlPhieuMuon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pnlPhieuMuonMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblSinhVien;
    private javax.swing.JPanel pnlLoaiSach;
    private javax.swing.JPanel pnlNguoiDung;
    private javax.swing.JPanel pnlPhieuMuon;
    private javax.swing.JPanel pnlSach;
    private javax.swing.JPanel pnlSinhVien;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPanel pnlView;
    // End of variables declaration//GEN-END:variables
}
